<?php
/**	op-layout-uqunie.com:/html.phtml
 *
 * @created   2017-08-04
 * @version   1.0
 * @package   op-layout-uqunie.com
 * @author    Tomoaki Nagahara
 * @copyright Tomoaki Nagahara All right reserved.
 */

 /** namespace
 *
 * @created   2020-07-11
 */
namespace OP;

?>
<html>
	<head>
		<?php
		OP::Template('layout/head.phtml');
		?>
	</head>
	<body id="body" class="body">
		<div id="container">
			<header>
				<a href="/">uqunie.com</a>
			</header>
			<article>
				<?php
				OP()->Unit()->App()->Content();
				?>
			</article>
			<footer>
				<p>Copyright 2006 uqunie Co., Ltd. All right reserved.</p>
				<p><a href="https://onepiece-framework.com">Powerd by ONEPIECE Framework</a></p>
			</footer>
		</div>
	</body>
</html>
