<?php
/**
 * op-layout-uqunie.com:/html.phtml
 *
 * @created   2017-08-04
 * @version   1.0
 * @package   op-layout-uqunie.com
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

 /** namespace
 *
 * @created   2020-07-11
 */
namespace OP;

/** use
 *
 * @created   2020-07-11
 */
use OP\UNIT\App;

?>
<!doctype html>
<html lang="<?= Env::Language() ?>">
	<head>
		<?php
		//	head
		App::Template('layout/head.phtml');
		App::Template('google/adsense.phtml');
		?>
	</head>
	<body id="body" class="body">
		<div id="container">
			<header>
				<a href="/">uqunie.com</a>
			</header>
			<article>
				<?php
				//	Main content
				App::Content();
				?>
			</article>
			<footer>
				<p>Copyright 2006 uqunie Co., Ltd. All right reserved.</p>
				<p><a href="https://onepiece-framework.com">Powerd by onepiece-framework</a></p>
			</footer>
		</div>
		<?= App::Template('google/analytics.phtml') ?>
	</body>
</html>
